### ISSUE TITLE
Le bouton pour valider la recherche n'a pas d'intitulé à l'intérieur

### ISSUE THREAD

**Issue by juliemoynat** [MTES-MCT/acceslibre#280]
Bonjour,

Le bouton pour valider la recherche possède un attribut `title` mais il est vide à l'intérieur. Par conséquent, selon la configuration des lecteurs d'écran, il peut arriver que ce bouton ne soit restitué que "bouton" (on m'a fait ce retour donc, oui, ça arrive !).

Par ailleurs, le nom est simplement "Rechercher". Il serait plus explicite que le nom soit "Rechercher un établissement".

Voici le code actuel :

```
<button type="submit" class="fr-col-2 fr-col-sm-1 fr-text--sm fr-btn btn-search" title="Rechercher">
        <span class="sr-only"></span>
</button>
```

Voici le code corrigé (à noter que l'attribut `title`, redondant, peut également être retiré à moins qu'il soit utile aux personnes qui utilisent la souris) :

```
<button type="submit" class="fr-col-2 fr-col-sm-1 fr-text--sm fr-btn btn-search" title="Rechercher un établissement">
        <span class="sr-only">Rechercher un établissement</span>
</button>
```

**Comment by mlvernay** [comment]
Fixed by https://github.com/MTES-MCT/acceslibre/commit/a1354c729eddf63ed5904bb2204ac91a5574bd9a
