### ISSUE TITLE
Un clic sur le bouton 'afficher la carte globale' peut retourner une 404

### ISSUE THREAD

**Issue by avieville** [MTES-MCT/acceslibre#364]
Bonjour,

Sur la page https://acceslibre.beta.gouv.fr/communes/ , lorsque l'on choisit une ville (ex:Paris) sans passer par le formulaire de recherche et que sur la page suivante https://acceslibre.beta.gouv.fr/recherche/75-paris/ on clique sur le bouton "Afficher la carte globale", une page 404 s'affiche car il manque le paramètre GET where dans l'URL.

>extrait de views.py
```python
def global_map(request, commune_slug=None):
    where, what, lat, lon, code = _clean_search_params(request.GET, "where", "what", "lat", "lon", "code")
    if not where:
        raise Http404()
```

En passant par le formulaire de recherche, les paramètres GET sont bien passés.

**Comment by mlvernay** [comment]
Bonjour,

Désolée, nous n'avions pas vu votre issue, cela a été corrigé entre temps. 

Merci pour votre contribution.
