### ISSUE TITLE
Ajout d'indications pour l'intérieur des lieux 

### ISSUE THREAD

**Issue by LASTkta** [MTES-MCT/acceslibre#438]
**Guichet d'accueil**

- Proche de l'entrée

- Hauteur adaptée (au moins une partie du comptoir à 80cm max de hauteur)

- Bande de guidage tactile jusqu’au guichet d'accueil (Contrastée visuellement)

- Allées larges (90cm minimum)

- Mobilier amovible (possibilité de déplacer les meubles)

**Plan du lieu proche de l'entrée**

- En relief

- Aux contrastes renforcés

- En braille

- En gros caractères

**Éclairage adapté (Pas de contre-jour, de zone d'éblouissement ou de pénombre)**

**Accès en fauteuil roulant**

- Total 

- Partiel (détailler les zones non accessibles) 

**Il y a plusieurs niveaux**

- Ascenseur (Grand, Standard, Petit)

- Annonce vocale des étages

- Commandes à hauteur de fauteuil roulant (entre 90 et 120cm du sol)

**Marche(s) / escaliers**

- Nombre de marches

- Hauteur de marche (cm)

- Main courante 

- Escalier mécanique

**Comment by mlvernay** [comment]
Bonjour,
Merci pour ces suggestions effectivement pertinentes. Cependant, nous nous concentrons sur un périmètre d'informations limitées afin de favoriser leur collecte et diffusion sur le web, dans une logique que le trop peut être l'ennemi du bien. Nous commençons progressivement à compléter ce premier niveau. Nous avons en effet récemment ajouté de nouveaux champs comme l'audiodescription ou encore la description d'une chambre adaptée. Ces ajouts sont amenés à se poursuivre et nous ne manquerons pas de nous inspirer de vos propositions.
Cordialement
