### ISSUE TITLE
Publication en opendata des données collectées ?

### ISSUE THREAD

**Issue by cquest** [MTES-MCT/acceslibre#80]
Une publication d'un dump des données collectées est-elle prévue ?
Si oui, quelle en sera la licence ?
Si non, pour quelle raison ?

**Comment by n1k0** [comment]
Salut Christian,

On fournit déjà une [api](https://acceslibre.beta.gouv.fr/api/docs/) paginéee qui permet de récupérer l'intégralité des données publiques, mais oui on peut tout à fait imaginer fournir un dump csv ou autre. Fallait juste qu'on trouve un premier "client" haha.

Côté licence je pensais partir sur ça https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf 

Preneur de tes retours et conseils :)

**Comment by cquest** [comment]
Un dump est complémentaire d'une récup paginée par API (plus simple pour beaucoup de monde).

Pour la licence, la LO c'est très bien, juste dommage car cela ne permettra pas de récupérer des infos depuis OpenStreetMap où des infos sur l'accessibilité (moins détaillées) sont disponibles sur plus de 200.000 objets (juste en France, plus pour le monde entier bien sûr). Des données ODbL ne pouvant être rediffusées en LO.

**Comment by n1k0** [comment]
Ongoing work in #160 and https://github.com/MTES-MCT/acceslibre-schema

**Comment by n1k0** [comment]
Les données ont été publiées en opendata : https://www.data.gouv.fr/fr/datasets/acceslibre/

Un schéma de données est disponible : https://schema.data.gouv.fr/MTES-MCT/acceslibre-schema/latest/documentation.html
